version: '3'
services:
  #  user-profile-service:
  #    build:
  #      context: .
  #      args:
  #        version: 0.0.1
  #      dockerfile: Dockerfile
  #    depends_on:
  #      - redis-server
  #      - mongodb-server
  #    ports:
  #      - "8080:8080"
  #    networks:
  #      - spring-boot-profile-network
  #    links:
  #      - redis-server
  #      - mongodb-server
  redis-server:
    image: redis
    command: [ "redis-server", "--protected-mode", "no" ]
    hostname: redis-server
    ports:
      - "6379:6379"
    networks:
      - spring-boot-profile-network
  mongodb-server:
    image: mongo
    restart: always
    hostname: localhost
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test123
    ports:
      - "27017:27017"
    networks:
      - spring-boot-profile-network
  rabbitmq-server:
    image: rabbitmq:3-management
    hostname: localhost
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - spring-boot-profile-network
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - spring-boot-profile-network
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - spring-boot-profile-network
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
    - 9411:9411
    networks:
      - trace

networks:
  trace:
    driver: bridge
  spring-boot-profile-network:
    driver: bridge